Move all OpenGL calls from SimulationView into SimulationViewGL. This is the right code organization, and avoids certain JDK's NoClassDefFoundError on GLEventListener.
The code layout is now:
	- OpenGL rendering in SimViewGL
	- Coordinate system, UI, and network all in SimView

Eventually I need to add a SimViewCPU class, that will render
the same volume data directly using CPU calls.