Fall back to simple Swing rendering if OpenGL isn't working right.
Several bad situations that should all "just work" now:
(1) No jogl.jar, just Java + Swing.  Can happen if jogl.jar isn't copied.
(2) Has jogl.jar, but bad native libraries.  E.g., didn't copy .so files, 32/64-bit mismatch between Java and libraries, etc.
(3) Working OpenGL, but so slow as to be unusable for 3D.  Common with Netbooks.
(4) Working OpenGL at reasonable rates.  Full 3D mode.

How I'm detecting these:
(1) Missing jogl.jar completely.  This will be a java.lang.NoClassDefFoundError
thrown when creating any class with GL stuff as members.

Can catch this like so:
		try {
			svGL=new SimulationViewGL();
		}
		catch (java.lang.NoClassDefFoundError e) {
			hasGL=false;
		}

This works nicely as long as *all* the OpenGL panels and such are created inside SimulationViewGL.

(2) Unhappy native libraries.  This will be a java.lang.UnsatisfiedLinkError thrown during the first
GLJPanel.paintComponent.

Can catch this at paint time like so:
	public void paint(Graphics g) {
		try {
			super.paint(g);
		} catch (java.lang.UnsatisfiedLinkError e) {
			svGL.remove(); /* make it so it won't paint again */
			System.out.println("Error loading JOGL native libraries.  Falling back to non-OpenGL rendering.");
			hasGL=false;
			svGL=null;
		}
	}

This still prints a diagnostic so users can fix it themselves, by removing "jogl.jar" and hence falling
back to case (1).

(3) Still using my code to time the rendering rate, and if it's too slow, we disable 3D mode.  This case
is frustratingly tricky to correct, because OpenGL has been started up and rendering before I can
determine that anything is wrong.  At that point, I'm fighting both JOGL and AWT's bone-headed event
system to tear out the JOGL renderer and put in the Swing one.  On NetBooks with ancient horribly buggy
OpenGL, this can kill the entire X server, so I'm leaving OpenGL on for now in this case, and only using
it for 2D rendering.  It'd be better to prune this off early, for example by looking at the "vendor
string".

Work on vendor string identification is ongoing.